name: Semantic PR
env:
  PIP_BREAK_SYSTEM_PACKAGES: 1
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  semantic:
    uses: RokctAI/shared-workflows/.github/workflows/universal-semantic.yml@main
    secrets: inherit
